name: build-LE12-chainbox
on:
  workflow_dispatch:
    inputs:
      le_periodic_version:
        description: "Version and Perodic builds"
        default: nightly
        required: true
        type: choice
        options:
          - nightly
          - official
      gitref_to_build:
        description: "gitref tag or hash to build"
        default: libreelec-12.0
        required: true
        type: string
      target:
        description: "targets to build"
        default: RK3328.L1
        required: true
        type: choice
        options:
          - all
          - RK3328.L1


env:
  clean_le: no_clean_le
  debug: debug
  ephemeral: ephemeral
  upload: upload

jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Checkout LibreELEC/LibreELEC.tv and check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: libreelec-12.0
          fetch-depth: 2
          repository: "${{ github.repository_owner }}/LibreELEC.tv"
          path: "LibreELEC.tv"
      - name: print latest_commit of checked out LibreELEC/LibreELEC.tv
        run: |
          cd LibreELEC.tv
          git rev-parse HEAD
      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: |
          cd LibreELEC.tv
          test -z "$(git rev-list --after='24 hours' $(git rev-parse HEAD))" && echo "should_run=false" >> $GITHUB_OUTPUT
          exit 0


  # Rockchip
  RK3328_L1-12_0:
    name: "RK3328.L1 12.0"
    # Only run if there has been a commit in the last 24 hours
    needs: check_date
    if: |
      ( needs.check_date.outputs.should_run != 'false' )
        && ( github.event.inputs.target == 'all' || github.event.inputs.target == 'RK3328.L1' || github.event_name == 'schedule' )
    uses: ./.github/workflows/yml-uses-make-image-LE12-chainbox.yml
    with:
      clean_le: no_clean_le
      debug: debug
      ephemeral: ephemeral
      upload: upload
      buildcmd: "make image"
      gitref: ${{ github.event.inputs.gitref_to_build || 'libreelec-12.0' }}
      group: RK3328_aarch64-12_0
      project: Rockchip
      arch: aarch64
      device: RK3328
      targetbuilddir: build.LibreELEC-RK3328.aarch64-12.0-devel
      buildperiodic: ${{ github.event.inputs.le_periodic_version || 'nightly' }}
      ccachecachesize: 10G
      version: "12.0"
      file_extension: img.gz,tar
    secrets: inherit
